export const SERVER_IP = import.meta.env.VITE_SERVER_IP
//export const SERVER_IP = "http://192.168.1.37:8000"
//export const SERVER_IP = "https://golocalbackend.onrender.com"
//export const SERVER_IP = "http://192.168.0.93:8000"
export const API_BASE_URL = `${SERVER_IP}/api`
export const TOKEN_STORAGE_KEY = "access"
export const REFRESH_TOKEN_STORAGE_KEY = "refresh"
export const logoColor = "#FA5039" 
export const backgroundColor= "#FEEDEB"
export const orangeColor ='#FA9339'
export const orangeColorLight =  '#FBA860'